version: "3.3"
services:
  front:
    build: ./front
    container_name: frontend
    ports:
      - "80:5000"

  back:
    build: ./back
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - AMADEUS_CLIENT_ID=${AMADEUS_CLIENT_ID}
      - AMADEUS_CLIENT_SECRET=${AMADEUS_CLIENT_SECRET}
      - PORT=3000
      - CORS_ALLOW="localhost:5000"
      - ENV=AWS_PROD
