version: "3.3"
services:
  front:
    build: ./front
    container_name: frontend
    ports:
      - "80:5000"

  back:
    build: ./back
    container_name: backend
    env_file:
      - .env
    ports:
      - "3000:3000"
