version: "3.9"
services:
  front:
    build: ./front
    container_name: frontend
    ports:
      - "5000:5000"

  back:
    build: ./back
    container_name: backend
    ports:
      - "3000:3000"
  
  nginx:
    depends_on:
      - front
      - back
    image: nginx:alpine
    container_name: nginx
