name: AWS CI/CD
on:
  push:
      branches:
        - AWS
        
jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout AWS branch
        uses: actions/checkout@v3
        with:
          ref: AWS

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
    
      - name: Build backend
        working-directory: ./back
        env:
          AMADEUS_CLIENT_ID: ${{ secrets.AMADEUS_CLIENT_ID }}
          AMADEUS_CLIENT_SECRET: ${{ secrets.AMADEUS_CLIENT_SECRET }}
          PORT: 3000
          CORS_ALLOW: localhost:5000
          ENV: GITHUB
        run: | 
          npm install
          npm run serve 
    
      - name: Build frontend
        working-directory: ./front
        run: |
          npm install
          npm run build

  deploy:
    name: Deploy to AWS EC2 instance
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Create CodeDeploy deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name FlightCalendarApp \
            --deployment-group-name FlightCalendarAppGroup \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}


