name: AWS CI/CD
on:
  push:
      branches:
        - AWS
        
jobs:
  build:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout AWS branch
        uses: actions/checkout@v3
        with:
          ref: AWS

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
    
      - name: Build backend
        working-directory: ./back
        env:
          AMADEUS_CLIENT_ID: ${{ secrets.AMADEUS_CLIENT_ID }}
          AMADEUS_CLIENT_SECRET: ${{ secrets.AMADEUS_CLIENT_SECRET }}
        run: | 
          npm install
          npm run serve 
    
      - name: Build frontend
        working-directory: ./front
        run: |
          npm install
          npm run build

